name: Flutter Size Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  size-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK with analyze-size
        run: flutter build apk --release --analyze-size --target-platform android-arm64

      - name: Extract size from analyze-size report
        id: apk_size
        run: |
          JSON_FILE=$(find ~/.flutter-devtools -name "apk-code-size-analysis_*.json" | head -n 1)
          if [ -z "$JSON_FILE" ]; then
            echo "No analyze-size JSON found"
            exit 1
          fi
          
          # Extract the total compressed size
          SIZE=$(jq '.summary.totalCompressedBytes' "$JSON_FILE")
          echo "Found size: $SIZE bytes from $JSON_FILE"

          echo "apk_size=$SIZE" >> $GITHUB_OUTPUT
          echo "report_file=$JSON_FILE" >> $GITHUB_OUTPUT

      - name: Gather commit info
        id: commit_info
        run: |
          COMMIT=$(git rev-parse HEAD)
          MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
          DATE=$(git log -1 --pretty=%cd --date=short)
          COMMITTER=$(git log -1 --pretty=%an)
          TAG=$(git describe --tags --exact-match $COMMIT 2>/dev/null || echo null)
          IS_RELEASE=false
          if [ "$TAG" != "null" ]; then IS_RELEASE=true; fi

          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "commitMessage=$MESSAGE" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "committer=$COMMITTER" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "isRelease=$IS_RELEASE" >> $GITHUB_OUTPUT

      - name: Calculate size diff from last commit
        id: size_diff
        run: |
          JSON_FILE="docs/app_size.json"
          if [ ! -f "$JSON_FILE" ]; then echo "[]" > "$JSON_FILE"; fi
          PREV_SIZE=$(jq '.[-1]?.size // 0' "$JSON_FILE")
          CURR_SIZE=${{ steps.apk_size.outputs.apk_size }}
          SIZE_DIFF=$((CURR_SIZE - PREV_SIZE))
          echo "prev_size=$PREV_SIZE" >> $GITHUB_OUTPUT
          echo "size_diff=$SIZE_DIFF" >> $GITHUB_OUTPUT

      - name: Update app_size.json
        run: |
          JSON_FILE="docs/app_size.json"

          jq --arg commit "${{ steps.commit_info.outputs.commit }}" \
             --arg commitMessage "${{ steps.commit_info.outputs.commitMessage }}" \
             --arg date "${{ steps.commit_info.outputs.date }}" \
             --arg committer "${{ steps.commit_info.outputs.committer }}" \
             --argjson size ${{ steps.apk_size.outputs.apk_size }} \
             --argjson sizeDiff ${{ steps.size_diff.outputs.size_diff }} \
             --arg isRelease "${{ steps.commit_info.outputs.isRelease }}" \
             '. + [{
                commit: $commit,
                commitMessage: $commitMessage,
                date: $date,
                size: $size,
                sizeDiff: $sizeDiff,
                committer: $committer,
                isRelease: ($isRelease == "true")
             }]' "$JSON_FILE" > tmp.json && mv tmp.json "$JSON_FILE"

      - name: Commit and push app_size.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update app_size.json [ci skip]"
          file_pattern: docs/app_size.json